log:
    debug: false
    
user:
    username: username

mongo:
    host: localhost
    port: 27017
    db: sicken

rabbitmq:
    host: localhost
    port: 5672
    user: sicken-gui
    password: password