deepseek:
  api_key: deepseek_api_key_here


sicken:
  temperature: 1.3
  model: deepseek-chat
  
  seed: 76
  frequency_penalty: null
  presence_penalty: null
  top_p: null
  top_logprobs: null

log:
  debug: false

mongo:
  host: localhost
  port: 27017
  db: sicken

rabbitmq:
  host: localhost
  port: 5672
  user: sicken-deepseek_llm
  password: password
