CONCURRENT_MAIN_CONFIG:
  nt: "C:\\sicken_reloaded\\configs\\sicken-concurrent.yaml"
  posix: '/opt/sicken_reloaded/configs/sicken-concurrent.yaml'

CONCURRENT_WORKERS_CONFIG:
  nt: "C:\\sicken_reloaded\\configs\\sicken-concurrent_workers.yaml"
  posix: /opt/sicken_reloaded/configs/sicken-concurrent_workers.yaml

CONCURRENT_MAIN_DIRECTORY:
  nt: "C:\\sicken_reloaded"
  posix: /opt/sicken_reloaded

CONCURRENT_WORKERS_DIRECTORY:
  nt: "C:\\sicken_reloaded\\workers"
  posix: /opt/sicken_reloaded/workers

CONCURRENT_LOGS_DIRECTORY:
  nt: "C:\\sicken_reloaded\\logs"
  posix: /opt/sicken_reloaded/logs

CONCURRENT_MODULES_DIRECTORY:
  nt: "C:\\sicken_reloaded\\modules"
  posix: /opt/sicken_reloaded/modules

EVENTS_FILE_PATH:
  nt: "C:\\sicken_reloaded\\configs\\events.yaml"
  posix: /opt/sicken_reloaded/configs/events.yaml

COMMANDS_HELP_FILE:
  nt: "C:\\sicken_reloaded\\files\\sicken\\commands_help.yaml"
  posix: /opt/sicken_reloaded/files/sicken/commands_help.yaml