openai:
  api_key: openai_api_key
  
user:
  admin_username: username

sicken:
  temperature: 1.3
  model: gpt-5.1
  
  seed: 76
  frequency_penalty: null
  presence_penalty: null
  top_p: null
  top_logprobs: null

log:
  debug: false

mongo:
  host: localhost
  port: 27017
  db: sicken

rabbitmq:
  host: localhost
  port: 5672
  user: sicken-openai_llm
  password: password
