# Log worker of Sicken. Responsible to store the log reports from the workers. This one doesn't store the logs of the sicken-concurrent - sicken-concurent is having a separate log system
sicken-log_worker:
  enable: true
  workers_count: 1
  uid: 7676
  gid: 7676

# Events brooker for Sicken.
sicken-events:
  enable: true
  workers_count: 1
  uid: 7676
  gid: 7676

# An OpenAI worker for Sicken. To run Sicken, at least one of the worker with suffix _llm have to be on.
sicken-openai_llm_commands:
  enable: false
  workers_count: 1
  uid: 7676
  gid: 7676

# A DeepSeek worker for Sicken. To run Sicken, at least one of the worker with suffix _llm have to be on.
sicken-deepseek_llm_commands:
  enable: true
  workers_count: 1
  uid: 7676
  gid: 7676
  

# A GUI for Sicken - to be used with Vtube Studio.
sicken-gui:
  enable: True
  workers_count: 1
  uid: 7676
  gid: 7676

# Classification mechanism, responsible for memory of Sicken. Basen on OpenAI
sicken-classification:
  enable: true
  workers_count: 5
  uid: 7676
  gid: 7676

#Commands in the GUI app
sicken-commands:
  enable: true
  workers_count: 1
  uid: 7676
  gid: 7676

sicken-agent_server:
  enable: true
  workers_count: 1
  uid: 7676
  gid: 7676