agent_server:
  host: 10.0.0.150
  port: 9999
  secret: 3dgawetsdagasdgsda

log:
  debug: true
    
mongo:
  host: localhost
  port: 27017
  db: sicken

rabbitmq:
  host: localhost
  port: 5672
  user: sicken-chat_viewer
  password: password
